version: "3.8"

networks:
  proxy:
    name: proxy
    external: true

services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8081, 0.0.0.0:8444 ssl'
      KONG_DECLARATIVE_CONFIG: '/opt/kong/kong.yml'
    command: "kong start"
    ports:
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./config/kong/kong.yml:/opt/kong/kong.yml
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
