version: "3.8"

networks:
  local:
  proxy:
    name: proxy
    external: true

services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
    env_file:
      - .env
    environment:
      TZ: ${TZ:-Etc/UTC}
    networks:
      - local
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - local

volumes:
  caddy_data:
  caddy_config: